Refactor of KM slope branch
JoffreyDorville/openmc pull request #1
Opened 2022-04-26 22:14 UTC by paulromano

Hi @JoffreyDorville! Here's the result of some refactoring I did on your branch. I tried to simplify things a bit in kalbach_mann.py which resulted in the reduction of many lines of code. I left in the `AtomicRepresentation` class but made it an "implementation detail" by putting a leading underscore (this indicates that it's not intended for consumption by normal users). At some point, we may want to extend the functionality, make it public, and use it elsewhere in the data module. It would certainly be useful in some places.

Lastly, I got rid of the test that relies on NJOY since those are longer running. I think the ENDF-HDF5 one is good enough and will run quickly on our CI resources.

I still have a few comments/questions on your branch, but if you merge this here, we can continue the discussion on your original pull request.

2022-06-30 00:23 UTC, JoffreyDorville requested changes
Hi Paul, I just finished the review. I requested some minor changes and wanted to see what you think of the last comment regarding the fact that the HDF5 test can be a problem in the future. Let me know if you have any questions.

2022-06-30 00:23 UTC, JoffreyDorville commented on openmc/data/kalbach_mann.py
> +    # Appendix H, Table 3)
```suggestion
    # Appendix H, Table 3) in MeV
```
I would specify the unit here to clarify

2022-06-30 00:23 UTC, JoffreyDorville commented on openmc/data/kalbach_mann.py
> +    I_b = za_to_breaking_energy[particle.za]
```suggestion
    I_a = za_to_breaking_energy[particle.za]
```
For consistency with the equation in ENDF6 format

2022-06-30 00:23 UTC, JoffreyDorville commented on openmc/data/kalbach_mann.py
> +        I_b
```suggestion
        I_a
```
For consistency with the above modification

2022-06-30 00:23 UTC, JoffreyDorville commented on openmc/data/kalbach_mann.py
> +class _AtomicRepresentation(EqualityMixin):
This new implementation of _AtomicRepresentation is perfectly generic now which is great!
As long as we are OK with the fact that a user is able to modify "z" and/or "a" after instantiation with no consistency check (i.e., is z < a?) during the lifetime of the object, I think I have no comment on this class. In practice, I do not think that a user will deliberately modify that so this should not be a major issue.

2022-06-30 00:23 UTC, JoffreyDorville commented on openmc/data/kalbach_mann.py
> +def kalbach_slope(energy_projectile, energy_emitted, za_projectile,
I really like this new implementation: compact and efficient!

2022-06-30 00:23 UTC, JoffreyDorville commented on tests/unit_tests/test_data_kalbach_mann.py
>  def test_comparison_slope_hdf5(hdf5_filename, endf_type, endf_filename):
```suggestion
def test_comparison_slope_hdf5(hdf5_filename, endf_filename):
```
The tests won't pass without this correction.

2022-06-30 00:23 UTC, JoffreyDorville commented on tests/unit_tests/test_data_kalbach_mann.py
>          )
I think that the comparison with NJOY is a necessary test because the HDF5 test can lead to a situation where the HDF5 file used to cross-check has been previously created using the function kalbach_slope from ENDF data. I know that producing HDF5 data from ENDF is currently impossible, which means that the HDF5 test is sufficient now. But if this limitation is lifted in the future, there is no automatic safeguard. I don't see any good solution to this problem other than keeping the test and make it only available in CI tests.

2022-06-30 00:23 UTC, JoffreyDorville commented on tests/unit_tests/test_data_kalbach_mann.py
>      # Test instanciation errors
```suggestion
    # Test instantiation errors
```

2022-07-13 16:02 UTC, paulromano commented on openmc/data/kalbach_mann.py
> +class _AtomicRepresentation(EqualityMixin):
Right, as is this class is not meant to be visible to the user (hence the leading underscore). It's just an implementation detail so as long as we use it consistently, I don't see any issues.

2022-07-13 16:09 UTC, paulromano commented on tests/unit_tests/test_data_kalbach_mann.py
>          )
I'm not too worried about this hypothetical as there are no plans to move away from relying on NJOY. Our CI testing time is already too long in my opinion so unfortunately we can't keep adding more tests that do a bunch of NJOY runs (which take considerable time).

2022-07-25 21:47 UTC, merged